/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Container;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hajer1
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(800, 600));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(252, 250, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 30, 80));
        jSeparator1.setForeground(new java.awt.Color(0, 30, 80));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 460, 30));

        jButton4.setBackground(new java.awt.Color(0, 30, 80));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(250, 248, 242));
        jButton4.setText("Log Out");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 170, 60));

        jButton6.setBackground(new java.awt.Color(0, 30, 80));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(250, 248, 242));
        jButton6.setText("View Students");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 60));

        jButton7.setBackground(new java.awt.Color(0, 30, 80));
        jButton7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(250, 248, 242));
        jButton7.setText("Search/ Update");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, 60));

        addStudentButton.setBackground(new java.awt.Color(0, 30, 80));
        addStudentButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(250, 248, 242));
        addStudentButton.setText("Add Student");
        addStudentButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        addStudentButton.setBorderPainted(false);
        addStudentButton.setFocusPainted(false);
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 190, 60));

        jButton9.setBackground(new java.awt.Color(0, 30, 80));
        jButton9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(250, 248, 242));
        jButton9.setText("Delete Student");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 180, 60));

        jSeparator2.setBackground(new java.awt.Color(0, 30, 80));
        jSeparator2.setForeground(new java.awt.Color(0, 30, 80));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 40, 560));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 30, 80));
        jLabel3.setText(" ☆ Welcome to Student Management System ☆");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 460, 70));

        jSeparator3.setBackground(new java.awt.Color(0, 30, 80));
        jSeparator3.setForeground(new java.awt.Color(0, 30, 80));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 760, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 30, 80));
        jSeparator4.setForeground(new java.awt.Color(0, 30, 80));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 760, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 30, 80));
        jSeparator5.setForeground(new java.awt.Color(0, 30, 80));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int choice = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (choice == JOptionPane.YES_OPTION) {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof MainFrame) {
            MainFrame mainFrame = (MainFrame) window;
            mainFrame.showPanel("Login");
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.out.println("View Students button clicked!");
    try {
        // Debug: Print parent hierarchy
        Container parent = getParent();
        System.out.println("Current panel parent: " + parent);
        
        // Debug: Print window ancestor
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        System.out.println("Window ancestor: " + window);
        System.out.println("Window class: " + (window != null ? window.getClass().getName() : "null"));
        
        // Try the dialog approach - most reliable
        JDialog viewDialog = new JDialog();
        viewDialog.setTitle("View Students");
        viewDialog.setModal(true);
        viewDialog.setSize(900, 600);
        viewDialog.setLocationRelativeTo(this);
        
        // Try to get MainFrame if it exists
        MainFrame mainFrame = null;
        if (window instanceof MainFrame) {
            mainFrame = (MainFrame) window;
            System.out.println("Found MainFrame instance!");
        }
        
        ViewStudentsPanel viewPanel = new ViewStudentsPanel();
        viewDialog.add(viewPanel);
        viewDialog.setVisible(true);
        
        System.out.println("View Students panel opened successfully!");
        
    } catch (Exception ex) {
        System.err.println("Error opening View Students: " + ex.getMessage());
        ex.printStackTrace();
        
        JOptionPane.showMessageDialog(this,
            "Failed to open View Students.\nError: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    System.out.println("=== SEARCH/UPDATE BUTTON CLICKED ===");
    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    System.out.println("Window found: " + window);
    System.out.println("Window is MainFrame: " + (window instanceof MainFrame));
    
    if (window instanceof MainFrame) {
        MainFrame mainFrame = (MainFrame) window;
        System.out.println("Switching to SearchUpdatePanel...");
        mainFrame.showPanel("SearchUpdatePanel");
        System.out.println("Switch completed!");
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        System.out.println("=== ADD STUDENT BUTTON CLICKED ===");
    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    System.out.println("Window found: " + window);
    System.out.println("Window is MainFrame: " + (window instanceof MainFrame));
    
    if (window instanceof MainFrame) {
        MainFrame mainFrame = (MainFrame) window;
        System.out.println("Switching to AddStudentPanel...");
        mainFrame.showPanel("AddStudentPanel");
        System.out.println("Switch completed!");
    }
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window instanceof MainFrame) {
        MainFrame mainFrame = (MainFrame) window;
        mainFrame.showPanel("DeleteStudentPanel");
    }
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
