/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hajer1
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws IOException {
    initComponents();
     //setting the size of the frame
    setSize(800, 600);
    setResizable(false);
    setLocationRelativeTo(null);
    
    MainPanel.setSize(800,600);
    MainPanel.setLocation((getWidth()-MainPanel.getWidth())/2,(getHeight()-MainPanel.getHeight())/2);
    
    // Add all panels to CardLayout
    LoginPanel loginPanel = new LoginPanel();
    DashboardPanel dashboard = new DashboardPanel();
    AddStudentPanel addStudent = new AddStudentPanel();
    //ViewStudentsPanel viewStudents = new ViewStudentsPanel();
    SearchUpdatePanel searchUpdate = new SearchUpdatePanel();  
    DeleteStudentPanel deleteStudent = new DeleteStudentPanel();
    MainPanel.add(loginPanel, "Login");
    MainPanel.add(dashboard, "Dashboard");
    MainPanel.add(addStudent, "AddStudentPanel");
    //MainPanel.add(viewStudents, "ViewStudentsPanel");
    MainPanel.add(searchUpdate, "SearchUpdatePanel");
    MainPanel.add(deleteStudent, "DeleteStudentPanel");
    // Show dashboard first
    showPanel("Login");
    
    setSize(900, 700);
    setResizable(false);
    setLocationRelativeTo(null);
}
   public void showPanel(String panelName) {
        // Get the CardLayout from MainPanel
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) MainPanel.getLayout();
        // Show the panel with the specified name
        cardLayout.show(MainPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        MainPanel.setBackground(new java.awt.Color(252, 250, 247));
        MainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        MainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainPanel, new java.awt.GridBagConstraints());
        MainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
}
